sonar.projectKey=devjwham_mabinogi-mobile-partymatch
sonar.organization=devjwham-1

# 분석할 소스 코드 경로 (현재 루트 기준 전체)
sonar.sources=.

# 테스트 코드가 들어있는 폴더는 분석 대상에서 제외하고 '테스트'로 인식시키기
sonar.tests=server/tests
sonar.exclusions=server/node_modules/**, server/tests/**, server/server-old.js, public/**

# jest lcov 커버리지 경로 매핑
sonar.javascript.lcov.reportPaths=server/coverage/lcov.info

# 소스 코드 인코딩 설정
sonar.sourceEncoding=UTF-8

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=mabinogi-mobile-partymatch
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8